#!/usr/bin/env python3

import os
import random

import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd

LEARNING_RATE = 0.01
# https://xkcd.com/221/ - 4 is overused, as is 42
RANDOM_SEED = 221
random.seed(a=RANDOM_SEED)

DATA_SEA_SYN_TRAIN_CSV = "data/SeaSynTrain.csv"
DATA_SEA_SYN_TEST_CSV = "data/SeaSynTest.csv"

enable_debug = False

def debug(string):
    if (enable_debug):
        print(string)

def report(string):
    print(string)

# Markdown table accumulator
class Table:
    def header(self, *fields):
        self.doc = "|"
        for field in fields:
            self.doc += f" {field} |"
        self.doc += "\n"
        self.doc += "|"
        for field in fields:
            self.doc += " --- |"
        self.doc += "\n"
        return self

    def __init__(self):
        self.doc = ""

    def row(self, *values):
        self.doc += "|"
        for value in values:
            self.doc += f" {value} |"
        self.doc += "\n"
        return self

    def report(self):
        report(self.doc)

def start_table():
    table = Table()
    table.header("Model", "Epoch", "Accuracy")
    return table

cluster_colours = ['red', 'green', 'blue', 'orange', 'violet', 'yellow']

# plot the starting cut
def plot(df=None, title=None, filename=None):
    fig = plt.figure(figsize=(10,4))
    ax = fig.add_subplot(projection='3d')
    #cmap="Set1"
    #cmap="tab10"
    cmap=mpl.colors.ListedColormap(cluster_colours)
    norm=mpl.colors.BoundaryNorm(range(0,len(cluster_colours)), cmap.N)
    ax.scatter(df.attrib1, df.attrib2, df.attrib3, c=df.Class, s=20, cmap=cmap, norm=norm)
    plt.title(title)
    plt.grid(True)
    plt.tight_layout()
    if filename is not None:
        print(f"Saving file - {filename}")
        plt.savefig(filename + ".png")
    plt.show()

# Data format:
# attrib1, attrib2, attrib3, class
# attrib* => float
# class -> {0,1}
training_pd = None
test_pd = None
if os.path.exists(DATA_SEA_SYN_TRAIN_CSV) and os.path.exists(DATA_SEA_SYN_TEST_CSV):
    print("Loading datasets...")
    training_pd = pd.read_csv(DATA_SEA_SYN_TRAIN_CSV)
    test_pd = pd.read_csv(DATA_SEA_SYN_TEST_CSV)
    # example_pd = pd.read_csv("example.csv")

# assert that the data was loaded.
debug(training_pd)
debug(test_pd)

# Fix python keyword collision
def fixClass(df):
    df["Class"] = df["class"]
    df.drop(columns="class", inplace=True)

fixClass(training_pd)
fixClass(test_pd)

# example is used for testing, and, or, nand.
# example_pd["Class"] = example_pd["class"]
# plot(test_pd, "test data", "test")
# plot(training_pd, "train data", "train")

# Keep the activation functions separate from the Perceptron.
def threshold(value):
    return 1 if value >= 0 else 0

def update_weight(weight, error, learning_rate, input):
    return weight + learning_rate * error * input

# Perceptron supporting 3 inputs.
class Perceptron:
    def __init__(self, activation_fn, learning_rate):
        self.doc=""
        self.activation_fn = activation_fn
        self.weight_bias = random.uniform(-1,1)
        self.weight_a = random.uniform(-1,1)
        self.weight_b = random.uniform(-1,1)
        self.weight_c = random.uniform(-1,1)
        self.learning_rate = learning_rate

    def _activation(self, value):
        return self.activation_fn(value)

    def apply(self, a,b,c):
        return self._activation(-1 * self.weight_bias +
                                a * self.weight_a +
                                b * self.weight_b +
                                c * self.weight_c)

    def learn(self, a, b, c, y_true, y_pred):
        error = y_true - y_pred
        debug(f"error: {error}")
        debug(f"before: ({self.weight_bias}, {self.weight_a}, {self.weight_b}, {self.weight_c})")
        self.weight_bias = update_weight(self.weight_bias, error, self.learning_rate, -1)
        self.weight_a = update_weight(self.weight_a, error, self.learning_rate, a)
        self.weight_b = update_weight(self.weight_b, error, self.learning_rate, b)
        self.weight_c = update_weight(self.weight_c, error, self.learning_rate, c)
        debug(f"after:  ({self.weight_bias}, {self.weight_a}, {self.weight_b}, {self.weight_c})")

def train(dataset, perceptron, num_epochs):
    for i in range(num_epochs):
        for row in dataset.itertuples():
            y_true = row.Class
            a = row.attrib1
            b = row.attrib2
            c = row.attrib3
            y_pred = perceptron.apply(a, b, c)
            perceptron.learn(a, b, c, y_true, y_pred)

def test(dataset, perceptron):
    correct = 0
    for row in dataset.itertuples():
        y_true = row.Class
        y_pred = perceptron.apply(row.attrib1, row.attrib2, row.attrib3)
        if y_true == y_pred:
            correct += 1
    return correct / dataset.shape[0]

print("Perceptron, Linearly Separable")

table = start_table()
perceptron = Perceptron(lambda value: threshold(value), LEARNING_RATE)
total_epochs = 0
# Run a single training pass, stopping at epoch checkpoints and reporting
# test accuracy.
for report_epochs in (1, 5, 10, 15, 20, 50, 60, 80, 100, 120, 150, 200):
    train(training_pd, perceptron, report_epochs - total_epochs)
    test_accuracy = test(test_pd, perceptron)
    total_epochs = report_epochs
    table.row("Separable", report_epochs, test_accuracy)

table.report()
