# .zsh history management:
HISTFILE="$HOME/.zsh_history"
HISTSIZE=500000
SAVEHIST=500000

# Write to the history file immediately, not when the shell exits
setopt INC_APPEND_HISTORY
# Share history between all sessions
setopt SHARE_HISTORY
# Expire duplicate entries first when trimming history
setopt HIST_EXPIRE_DUPS_FIRST

# Kopia alias - keep it out of the path.
alias kopia=/Applications/KopiaUI.app/Contents/Resources/server/kopia
alias texstudio=/Applications/texstudio-4.9.2-osx-m1.app/Contents/MacOS/texstudio

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/opt/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/opt/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/opt/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

